routes/web.php
<?php
use Illuminate\Http\Request;

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
//Auth::loginUsingId(3524); // 6 Admin, 5 User

Auth::routes();
Route::impersonate();
Route::get('/impersonate/create', 'ImpersonateController@create')->name('impersonate.create');
Route::post('/impersonate/store', 'ImpersonateController@store')->name('impersonate.store');


Route::get('/test', function(){
    return view('test');
});
// Outside to except show in controller
Route::get('/tournaments/deleted', 'TournamentController@getDeleted')->name('getDeleted'); // Already has auth middleware
Route::resource('tournaments', 'TournamentController');


Route::get('/logout', 'Auth\LoginController@logout');

Route::post('auth/invite', 'Auth\RegisterController@registerFromInvite');


Route::get('/tournaments/{tournamentSlug}/invite/{token}', 'ChampionshipController@create'); //TODO this route has no sense
Route::post('tournaments/{tournament}/invite/{invite}/categories', 'ChampionshipController@store');

Route::get('lang/{lang}', 'LanguageController@update');
Route::get('tournaments/{tournament}/register', 'TournamentController@register')->name('register.category');

Route::group(['middleware' => ['guest']],
    function () {

        // Registration routes...
        Route::get('register/confirm/{token}', 'Auth\RegisterController@confirmEmail');

        //Social Login
        Route::get('/login/{provider?}', [
            'uses' => 'Auth\LoginController@getSocialAuth',
            'as' => 'auth.getSocialAuth'
        ]);


        Route::get('/login/callback/{provider?}', [
            'uses' => 'Auth\LoginController@getSocialAuthCallback',
            'as' => 'auth.getSocialAuthCallback'
        ]);
    });


Route::group(['middleware' => ['auth']], // 'throttle:100,1'
    function () {
        Route::get('/', 'DashboardController@index')->name('dashboard');
        Route::resource('federations', 'FederationController', ['names' => ['index' => 'federations.index', 'create' => 'federations.create', 'edit' => 'federations.edit', 'store' => 'federations.store', 'update' => 'federations.update']]);
        Route::resource('associations', 'AssociationController');
        Route::resource('clubs', 'ClubController', ['names' => ['index' => 'clubs.index', 'create' => 'clubs.create', 'edit' => 'clubs.edit', 'store' => 'clubs.store', 'update' => 'clubs.update']]);

        Route::resource('categories', 'CategoryController');

        //TODO those routes should not exist -- removing
        Route::resource('/tournaments/{tournament}/teams', 'TeamController', ['names' => ['index' => 'teams.index', 'create' => 'teams.create', 'edit' => 'teams.edit', 'store' => 'teams.store', 'update' => 'teams.update']]);

        Route::resource('users', 'UserController', ['names' => [
            'index' => 'users.index',
            'show' => 'users.show',
            'create' => 'users.create',
            'edit' => 'users.edit',
            'store' => 'users.store',
            'update' => 'users.update'
        ]]);

        Route::get('users/{user}/tournaments', [
            'uses' => 'UserController@getMyTournaments',
            'as' => 'users.tournaments'
        ]);


        Route::get('export', 'UserController@export');
        Route::resource('tournaments/{tournament}/users', 'CompetitorController', ['names' => ['index' => 'tournament.users.index', 'show' => 'tournament.users.show', 'create' => 'tournament.users.create', 'edit' => 'tournament.users.edit', 'store' => 'tournament.users.store', 'update' => 'tournament.users.update']]);
        Route::delete('tournaments/{tournamentId}/categories/{championshipId}/users/{userId}/delete', 'CompetitorController@deleteUser');
        Route::put('tournaments/{tournamentId}/categories/{championshipId}/users/{userId}/confirm', 'CompetitorController@confirmUser');

        Route::resource('invites', 'InviteController', ['names' => ['index' => 'invites.index', 'store' => 'invites.store', 'show' => 'invites.show']]);
        Route::post('invites/upload', 'InviteController@upload');
        Route::get('tournaments/{tournament}/invite', 'InviteController@create');


        Route::post('championships/{championship}/teams', 'TeamController@store')->name('team.store');


        // Other Admin Routes

        Route::get('logs', 'LogsController@index')->name('logs.index');
        Route::get('debug', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index')->name('debug.index');


//        Route::get('oauth', function(){
//           return view('auth/oauth2');
//        });

        Route::get('tournaments/{tournament}/trees/', 'TreeController@index')->name('tree.index');
        Route::get('tournaments/{tournament}/fights/', 'FightController@index')->name('fights.index');
        Route::get('championships/{championship}/tree/', 'TreeController@single')->name('tree.single');

        // PDF
        Route::get('championships/{championship}/tree/pdf', 'PDFController@tree')->name('tree_pdf');
        Route::get('championships/{championship}/scoresheet/pdf', 'PDFController@scoresheets')->name('sheet_pdf');

        Route::post('tournaments/{tournament}/trees/', 'TreeController@store')->name('tree.storeAll');
        Route::post('championships/{championshipId}/trees/', 'TreeController@store')->name('tree.store');;
        Route::put('championships/{championshipId}/trees/', 'TreeController@update')->name('tree.update');;

        Route::resource('tournaments/{tournament}/scoresheets', 'ScoreSheetController');


        Route::get('workingonit', function () {
            return view('workingonit');
        })->name('workingonit');



    });
Route::get('/auth/callback', function (Request $request) {
    $http = new GuzzleHttp\Client;

    $response = $http->post('https://laravel.dev/oauth/token', [
        'form_params' => [
            'grant_type' => 'authorization_code',
            'client_id' => '6',
            'client_secret' => 'A0srL90BUGWT0ATUeFFmDeiqTVkk4sH93PvMp5FS',
            'redirect_uri' => 'http://laravel.dev/auth/callback',
            'code' => $request->code,
        ],
    ]);

    return json_decode((string)$response->getBody(), true);
});


Auth::routes();

Route::get('/auth/oauth', function () {
    return view('auth.oauth');
});

Route::get('/oauth_test', function () {
    return view('oauth_ajax_test');
});

Route::get('/callback', function (Request $request) {
    $http = new GuzzleHttp\Client;

    $response = $http->post('https://laravel.dev/oauth/token', [
        'form_params' => [
            'grant_type' => 'authorization_code',
            'client_id' => '10',
            'client_secret' => 'LdI1CLUsWOqfsuyGApZSTbns0wQcoSpKE7LRzSPc',
            'redirect_uri' => 'https://laravel.dev/callback',
            'code' => $request->code,
        ],
    ]);

    return json_decode((string)$response->getBody(), true);
});

app/Http/Controllers/TournamentController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Country;
use App\Exceptions\InvitationNeededException;
use App\FightersGroup;
use App\Grade;
use App\Http\Requests\TournamentRequest;
use App\Http\Requests\VenueRequest;
use App\Tournament;
use App\TournamentLevel;
use App\Venue;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Lang;
use Illuminate\Support\Facades\Response;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\URL;


class TournamentController extends Controller
{
    public function __construct()
    {
        $this->middleware('ownTournament')->except('index', 'show', 'register');
        $this->middleware('auth')->except('show', 'register');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        if (Auth::user()->isSuperAdmin()) {
            $tournaments = Tournament::with('owner')
                ->withCount('competitors')
                ->orderBy('updated_at', 'desc')
                ->paginate(config('constants.PAGINATION')); // ,'uniqueTrees'
        } else {
            $tournaments = Auth::user()->tournaments()
                ->with('owner')->orderBy('updated_at', 'desc')
                ->paginate(config('constants.PAGINATION'));
        }
        $title = trans('core.tournaments_created');
        return view('tournaments.index', compact('tournaments', 'title'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $levels = TournamentLevel::getAllPlucked();
        $categories = Category::take(10)->orderBy('id', 'asc')->pluck('name', 'id');
        $tournament = new Tournament();
        $rules = config('options.rules');
        $rulesCategories = (new Category)->getCategorieslabelByRule();
        return view('tournaments.create', compact('levels', 'categories', 'tournament', 'rules', 'rulesCategories'));
    }

    /**
     * Store a new Tournament
     *
     * @param TournamentRequest $form
     * @return \Illuminate\Http\Response
     */
    public function store(TournamentRequest $form)
    {
        $tournament = $form->persist();
        $msg = trans('msg.tournament_create_successful', ['name' => $tournament->name]);
        flash()->success($msg);
        return redirect(URL::action('TournamentController@edit', $tournament->slug));
    }

    /**
     * Display the Tournament.
     *
     * @param Request $request
     * @param $tournamentSlug
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request, $tournamentSlug)
    {
        $teams = "";
        $grades = Grade::getAllPlucked();
        $tournament = FightersGroup::getTournament($request);
        $venue = $tournament->venue ?? new Venue;
        $countries = Country::getAll();

        return view('tournaments.show', compact('tournament', 'tournamentWithTrees', 'grades', 'teams', 'venue', 'countries'));
    }

    /**
     * Show the form for editing the Tournament.
     *
     * @param Tournament $tournament
     * @return \Illuminate\Http\Response
     */
    public function edit(Tournament $tournament)
    {

        $tournament = Tournament::with('competitors', 'championshipSettings', 'championships.settings', 'championships.category')
            ->withCount('competitors', 'teams')
            ->find($tournament->id);
        $selectedCategories = $tournament->categories->pluck('name','id'); // 3,4 ,240
        $defaultCategories = Category::take(7)->get()->sortBy('id')->pluck('name','id'); // 1 2 3 4 5 6 7

        $categories = $selectedCategories->union($defaultCategories)->toArray();



        // Statistics for Right Panel
        $countries = Country::getAllPlucked();
        $settingSize = $tournament->championshipSettings->count();
        $categorySize = $tournament->championships->count();
        $hanteiLimit = config('options.hanteiLimit');

        $grades = Grade::getAllPlucked();
        $venue = $tournament->venue ?? new Venue;
        $levels = TournamentLevel::getAllPlucked();

        return view('tournaments.edit', compact('tournament', 'levels', 'categories', 'settingSize', 'categorySize', 'grades', 'numCompetitors', 'rules', 'hanteiLimit', 'numTeams', 'countries', 'venue'));
    }

    /**
     * Update the Tournament in storage.
     *
     * @param TournamentRequest $request
     * @param VenueRequest $venueRequest
     * @param Tournament $tournament
     * @return \Illuminate\Http\JsonResponse
     */
    public function update(TournamentRequest $request, VenueRequest $venueRequest, Tournament $tournament)
    {
        //TODO Shouldn't I have a Policy???
        $venue = $tournament->venue;
        if ($venue == null)
            $venue = new Venue;

        if ($venueRequest->has('venue_name')) {
            $venue->fill($venueRequest->all());
            $venue->save();
        } else {
            $venue = new Venue();
        }
        $res = $request->update($tournament, $venue);

        if ($request->ajax()) {
            $res == 0
                ? $result = Response::json(['msg' => trans('msg.tournament_update_error', ['name' => $tournament->name]), 'status' => 'error'])
                : $result = Response::json(['msg' => trans('msg.tournament_update_successful', ['name' => $tournament->name]), 'status' => 'success']);
            return $result;
        } else {
            $res == 0
                ? flash()->success(trans('msg.tournament_update_error', ['name' => $tournament->name]))
                : flash()->success(trans('msg.tournament_update_successful', ['name' => $tournament->name]));
            return redirect(URL::action('TournamentController@edit', $tournament->slug))->with('activeTab', $request->activeTab);
        }
    }

    /**
     * Remove the Tournament from storage.
     *
     * @param Tournament $tournament
     * @return \Illuminate\Http\JsonResponse
     * @throws \Exception
     */
    public function destroy(Tournament $tournament)
    {
        if ($tournament->delete()) {
            return Response::json(['msg' => Lang::get('msg.tournament_delete_successful', ['name' => $tournament->name]), 'status' => 'success']);
        }
        return Response::json(['msg' => Lang::get('msg.tournament_delete_error', ['name' => $tournament->name]), 'status' => 'error']);
    }

    /**
     * @param $tournamentSlug
     * @return \Illuminate\Http\JsonResponse
     */
    public function restore($tournamentSlug)
    {
        $tournament = Tournament::withTrashed()->whereSlug($tournamentSlug)->first();
        if ($tournament->restore()) {
            return Response::json(['msg' => Lang::get('msg.tournament_restored_successful', ['name' => $tournament->name]), 'status' => 'success']);
        }

        return Response::json(['msg' => Lang::get('msg.tournament_restored_error', ['name' => $tournament->name]), 'status' => 'error']);

    }

    /**
     * Called when a user want to register an open tournament
     * @param Request $request
     * @param Tournament $tournament
     * @return mixed
     * @throws InvitationNeededException
     */
    public function register(Request $request, Tournament $tournament)
    {

        if (!Auth::check()) {
            Session::flash('message', trans('msg.please_create_account_before_playing', ['tournament' => $tournament->name]));
            return redirect(URL::action('Auth\LoginController@login'));
        }
        if ($tournament->isOpen() && Auth::check()) {
            App::setLocale(Auth::user()->locale);

            $grades = Grade::getAllPlucked();
            $tournament = Tournament::with('championships.category', 'championships.users')->find($tournament->id);
            return view("categories.register", compact('tournament', 'invite', 'currentModelName', 'grades'));
        }

        throw new InvitationNeededException();
    }

    /**
     * Get Deleted Tournaments
     * 
     * @return mixed
     */
    public function getDeleted()
    {
        $tournaments = Auth::user()->tournaments()->with('owner')
        ->onlyTrashed()
        ->latest()
        ->paginate(config('constants.PAGINATION'));

        if (Auth::user()->isSuperAdmin()) {
            $tournaments = Tournament::onlyTrashed()->with('owner')
                ->has('owner')
                ->latest()
                ->paginate(config('constants.PAGINATION'));
        }

        $title = trans('core.tournaments_deleted');
        return view('tournaments.deleted', compact('tournaments', 'title'));
    }


}

resources/views/tournaments/categories.blade.php
@extends('layouts.dashboard')

@section('content')



    <div class="tabbable">

        <ul class="nav nav-tabs nav-tabs-bottom bottom-divided nav-justified">
            <?php use Xoco70\LaravelTournaments\Models\ChampionshipSettings;$first = true ?>
            @foreach($categories  as $category)
                <li {{$first ? 'class=active':'' }}>
                    <?php $first = false ?>
                    <a href="#{{$category->id}}" data-toggle="tab">{{Lang::get($category->name) }}</a></li>
            @endforeach
        </ul>
        <div class="row">
            <div class="col-md-8 col-md-offset-2 col-lg-6 col-lg-offset-3">
                <div class="tab-content">
                    <?php  $first = true ?>
                    @foreach($categories as $category)
                        <div class="tab-pane {{$first ? 'active':'' }}" id="{{$category->id}}">
                        <?php $first = false;
                        $championshipSettings = ChampionshipSettings::where("tournament_id", $tournamentId)
                                ->where("category_id", $category->id)
                                ->first();

                        ?>
                        <!-- TAB CATEGORIES DEFAULT SETTING -->
                        @if (is_null($championshipSettings))
                            {!! Form::open(["route" => "tournaments.{tournamentId}.categorySettings.store"]) !!}
                        @else
                            {!! Form::model($championshipSettings, array('route' => array('tournaments.{tournamentId}.categorySettings.update', $championshipSettings->id), 'method' => 'PATCH')) !!}
                        @endif

                        {!! Form::hidden('tournament_id', $tournamentId) !!}
                        {!! Form::hidden('category_id', $category->id) !!}
                        @include('categories.categorySettings')
                        {!! Form::close() !!}
                        <!-- END TAB CATEGORIES DEFAULT SETTING -->
                        </div>
                    @endforeach


                </div>
            </div>
            <script>
                $(".switch").bootstrapSwitch();
            </script>

            @include("errors.list")
        </div>
    </div>

@stop

resources/views/tournaments/create.blade.php
@extends('layouts.dashboard')
@section('title')
    <title>{{ trans('core.create_new_tournament')  }}</title>
@stop

@section('breadcrumbs')
    {!! Breadcrumbs::render('tournaments.create',trans_choice('core.tournament', 1)) !!}
@stop
@section('content')

    @include("errors.list")

    <div class="container-fluid">

        {!! Form::open(['url'=> URL::action('TournamentController@store') ]) !!}

        @include("tournaments.form", ["submitButton" => trans('core.add').' '. trans_choice('core.tournament',1) ])


        {!! Form::close()!!}
        @include("modals.create_category")

    </div>
@stop
<?php
$now = Carbon\Carbon::now();
$year = $now->year;
$month = $now->month - 1; // Javascript dates are zero-indexed https://github.com/amsul/pickadate.js/issues/768
$day = $now->day;

?>

@section('scripts_footer')
    {!! Html::script('js/pages/header/tournamentCreate.js') !!}
    {!! JsValidator::formRequest('App\Http\Requests\TournamentRequest') !!}

    <script>
        var ikf_categories = "{!!   trans_choice('categories.category',2) .": ". implode(', ',$rulesCategories[0]) !!}";
        var ekf_categories = "{!!   trans_choice('categories.category',2) .": ".implode(', ',$rulesCategories[1]) !!}";
        var lakc_categories = "{!!  trans_choice('categories.category',2) .": ".implode(', ',$rulesCategories[2]) !!}";

        var dualList = $('.listbox-filter-disabled').bootstrapDualListbox({
            showFilterInputs: false,
            infoTextEmpty: '',
            infoText: ''
        });
        $('.listbox-filter-disabled').on('change', function () {
            disableSubmit();
        });
        var dualListIds = [];


        var minDay = new Date("{{$year}}", "{{$month}}", "{{$day}}", 0, 0, 0, 0);
        $(function () {

            var $input = $('.dateFin').pickadate({
                min: minDay,
                format: 'yyyy-mm-dd',
                today: '',
                clear: '',
                close: ''
            });
            var pickerFin = $input.pickadate('picker');

            var $inputIni = $('.dateIni').pickadate({
                min: [{{$year}}, {{$month}}, {{$day}}],
                format: 'yyyy-mm-dd',
                today: '',
                clear: '',
                close: '',

                onSet: function () {
                    if (this.get('select') != null)
                        pickerFin.set('min', this.get('select'));
                }
            });
            var pickerIni = $inputIni.pickadate('picker');

            $(".listbox-filter-disabled > option").each(function () {
                dualListIds.push(this.value);
            });


            $('select[name="category[]_helper1"]').prop('disabled', true);
            $('select[name="category[]_helper2"]').prop('disabled', true);
            $('#create_category_link').bind('click', false);

            $('#c1').on('click', function () {
                $('.btn-success').prop('disabled', false);

                $('select[name="category[]_helper1"]').prop('disabled', true);
                $('select[name="category[]_helper2"]').prop('disabled', true);
                $('#create_category_link').bind('click', false);

                $('select[name="rule_id"]').prop('disabled', false);
                $('select[name="rule_id"]').prop('disabled', false);


            });

            $('#c2').on('click', function () {
                disableSubmit();
                $('.btn-success').prop('disabled', true);
                $('select[name="category[]_helper1"]').prop('disabled', false);
                $('select[name="category[]_helper2"]').prop('disabled', false);
                $('#create_category_link').unbind('click', false);
                $('select[name="rule_id"]').prop('disabled', true);

            });

            $('#rules').on('change', function () {
                if (this.value == 0) {
                    $('#categories_desc').text("");
                }
                else if (this.value == 1) {
//                    console.log(ikf_categories);
                    $('#categories_desc').text(ikf_categories);
                } else if (this.value == 2) {
//                    console.log(ekf_categories);
                    $('#categories_desc').text(ekf_categories);
                } else if (this.value == 3) {
//                    console.log(lakc_categories);
                    $('#categories_desc').text(lakc_categories);
                }
            });


        });

        function disableSubmit() {
            if ($('select[name="category[]_helper2"]').text() == "") {
                $('.btn-success').prop('disabled', true);
            } else {
                $('.btn-success').prop('disabled', false);
            }
        }
    </script>
@stop

resources/views/tournaments/deleted.blade.php
@extends('layouts.dashboard')
@section('breadcrumbs')
    {!! Breadcrumbs::render('tournaments.deleted') !!}

@stop

@section('content')
    @include("layouts.tournamentList")
    @include("errors.list")
@stop


@section("scripts_footer")
    <script>
        var url ="{{ route('tournaments.index') }}";
        var url_restore ="{{ route('api.tournaments.index') }}";
    </script>
    {!! Html::script('js/pages/header/tournamentIndex.js') !!}
    {!! Html::script('js/pages/footer/tournamentDeletedFooter.js') !!}
@stop

resources/views/tournaments/edit.blade.php
@extends('layouts.dashboard')
@section('styles')
    {!! Html::style('css/pages/tournamentEdit.css')!!}
@stop
<?php
$favicon = asset('/favicon_kz-01.png');
?>
@section('title')
    <title>{{ trans('core.edit') .' '.trans_choice('core.tournament',1) }}</title>
@stop
@section('breadcrumbs')
    {!! Breadcrumbs::render('tournaments.edit',$tournament) !!}

@stop
@section('content')
    @include("errors.list")
    <?php
    $appURL = (app()->environment() == 'local' ? getenv('URL_BASE') : config('app.url'));
    ?>
    <!-- Detached content -->
    <div class="container-detached">
        <div class="content-detached">
            <ul class="nav nav-tabs nav-tabs-solid nav-justified">
                <li class="active"><a href="#general" data-toggle="tab" id="tab1">{{trans('core.general_data')}}</a>
                </li>
                <li><a href="#venue" data-toggle="tab" id="tab2">{{trans('core.venue')}}</a></li>
                <li><a href="#categories" data-toggle="tab" id="tab3">{{trans_choice('categories.category',2)}}</a></li>
                <li><a href="#category_setting" data-toggle="tab"
                       id="tab4">{{trans_choice('categories.categorySettings',2)}}</a></li>

            </ul>

            <div class="row">
                <div class="col-lg-12">

                    <!-- Simple panel 1 : General Data-->


                    <div class="tab-content">

                        <div class="tab-pane active" id="general">
                            @include("layouts.tournament.general")
                        </div>

                        <div class="tab-pane" id="venue">
                            @include("layouts.tournament.venue")
                        </div>
                        <div class="tab-pane" id="categories">
                            @include("layouts.tournament.categories")

                        </div>
                        <div class="tab-pane" id="category_setting">
                            @include("layouts.tournament.categories_settings")
                        </div>
                    </div>
                </div>
                <!-- /simple panel acordion -->
            </div>
        </div>
        <!-- /detached content -->
    </div>
    @include("right-panel.tournament_menu")

    @include("modals.create_category")

    <!-- /content area -->
    <?php
    $now = Carbon\Carbon::now();
    $year = $now->year;
    $month = $now->month - 1; // Javascript dates are zero-indexed https://github.com/amsul/pickadate.js/issues/768
    $day = $now->day;

    $venue = $venue->setDefaultLocation($tournament, $venue->latitude, $venue->longitude);
    if (session()->has('activeTab')) {
        $activeTab = session('activeTab');
    }
    ?>

@stop

@section('scripts_footer')
    <script>
                {{--        var moreText = "{{trans('core.see_more') }}";--}}
                {{--        lessText = "{{trans('core.see_less') }}";--}}

        var url_base = "{{ route('tournaments.index') }}";
        var url_api_base = "{{ route('api.tournaments.index') }}";
        var url_api_root = "{{ route('api.root') }}";
        var url_edit = "{{ URL::action('TournamentController@update', $tournament->slug) }}";
        var longitude = "{{$venue->longitude }}";
        var latitude = "{{$venue->latitude }}";
        var configured = "{{ trans('core.configured_full') }}";
        var allCategoriesSize = '{!! $categorySize !!}';
        var dualListIds = [];
        var dualList;
        var icon;
        var venue = "{!! addcslashes($venue, '"') !!}";
        var facebook_id = "{{ env('FACEBOOK_CLIENT_ID') }}";
        var url_register = '{{ URL::action('TournamentController@register',$tournament->slug) }}';
        var url_show_tournament = '{{ URL::action('TournamentController@show',$tournament->slug) }}';

                @if (isset($activeTab))
        var activeTab = "{{ $activeTab }}";

        @endif
            venue = JSON.parse(venue);

        $("a").on('click', function () {

            var href = $(this).attr('href');
            if (href != null && href.indexOf('#') != -1) {
                var id = href.replace("#", "");
                if ($("a[data-toggle='tab'][id='" + id + "']")) {
                    $("#" + id).click();
                }
            }

        });


        window.twttr = (function (d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0],
                t = window.twttr || {};
            if (d.getElementById(id)) return t;
            js = d.createElement(s);
            js.id = id;
            js.src = "https://platform.twitter.com/widgets.js";
            fjs.parentNode.insertBefore(js, fjs);

            t._e = [];
            t.ready = function (f) {
                t._e.push(f);
            };

            return t;
        }(document, "script", "twitter-wjs"));
    </script>


    {!! Html::script('js/pages/header/tournamentEdit.js') !!}
    {!! Html::script('https://maps.google.com/maps/api/js?key=AIzaSyDMbCISDkoc5G1AP1mw8K76MsaN0pyF64k&libraries=places') !!}


@stop

resources/views/tournaments/index.blade.php
@extends('layouts.dashboard')
@section('title')
    <title>{{ trans_choice('core.tournament',2) }}</title>
@stop

@section('breadcrumbs')
    {!! Breadcrumbs::render('tournaments.index') !!}

@stop

@section('content')
    @include("layouts.tournamentList")
    @include("errors.list")
@stop
@section("scripts_footer")
    <script>

        var url ="{{ route('tournaments.index') }}";
        var url_restore ="{{ route('api.tournaments.index') }}";

    </script>
    {!! Html::script('js/pages/header/footable.js') !!}
    {!! Html::script('js/pages/footer/tournamentIndexFooter.js') !!}
@stop

resources/views/tournaments/show.blade.php
@extends('layouts.guest_banner')
@section('content')
    <?php
    $appURL = (app()->environment() == 'local' ? getenv('URL_BASE') : config('app.url'));
    ?>

    @include('layouts.tournament.show.top')


    <div class="row">


        <!-- Simple panel 1 : General Data-->


        <div class="tab-content">
            <div class="tab-pane active" id="trees">
                @include("layouts.tournament.show.trees")
            </div>
            <div class="tab-pane " id="general">
                @include("layouts.tournament.show.general")
            </div>
            <div class="tab-pane" id="competitors">
                @include("layouts.tournament.show.competitors")
            </div>
            <div class="tab-pane" id="rules">
                @include("layouts.tournament.show.rules")
            </div>
        </div>

    </div>

    <!-- Detached content -->

    <?php
    $venue = $venue->setDefaultLocation($tournament, $venue->latitude, $venue->longitude);
    ?>
    <!-- /content area -->

@stop

@section('scripts_footer')
    <script>

        let latitude = "{{ $venue->latitude }}";
        let longitude = "{{ $venue->longitude }}";
    </script>
    {!! Html::script('js/pages/header/tournamentShow.js') !!}
    {!! Html::script('https://maps.google.com/maps/api/js?key=AIzaSyDMbCISDkoc5G1AP1mw8K76MsaN0pyF64k') !!}

@stop