routes/web.php
<?php
use Illuminate\Http\Request;

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
//Auth::loginUsingId(3524); // 6 Admin, 5 User

Auth::routes();
Route::impersonate();
Route::get('/impersonate/create', 'ImpersonateController@create')->name('impersonate.create');
Route::post('/impersonate/store', 'ImpersonateController@store')->name('impersonate.store');


Route::get('/test', function(){
    return view('test');
});
// Outside to except show in controller
Route::get('/tournaments/deleted', 'TournamentController@getDeleted')->name('getDeleted'); // Already has auth middleware
Route::resource('tournaments', 'TournamentController');


Route::get('/logout', 'Auth\LoginController@logout');

Route::post('auth/invite', 'Auth\RegisterController@registerFromInvite');


Route::get('/tournaments/{tournamentSlug}/invite/{token}', 'ChampionshipController@create'); //TODO this route has no sense
Route::post('tournaments/{tournament}/invite/{invite}/categories', 'ChampionshipController@store');

Route::get('lang/{lang}', 'LanguageController@update');
Route::get('tournaments/{tournament}/register', 'TournamentController@register')->name('register.category');

Route::group(['middleware' => ['guest']],
    function () {

        // Registration routes...
        Route::get('register/confirm/{token}', 'Auth\RegisterController@confirmEmail');

        //Social Login
        Route::get('/login/{provider?}', [
            'uses' => 'Auth\LoginController@getSocialAuth',
            'as' => 'auth.getSocialAuth'
        ]);


        Route::get('/login/callback/{provider?}', [
            'uses' => 'Auth\LoginController@getSocialAuthCallback',
            'as' => 'auth.getSocialAuthCallback'
        ]);
    });


Route::group(['middleware' => ['auth']], // 'throttle:100,1'
    function () {
        Route::get('/', 'DashboardController@index')->name('dashboard');
        Route::resource('federations', 'FederationController', ['names' => ['index' => 'federations.index', 'create' => 'federations.create', 'edit' => 'federations.edit', 'store' => 'federations.store', 'update' => 'federations.update']]);
        Route::resource('associations', 'AssociationController');
        Route::resource('clubs', 'ClubController', ['names' => ['index' => 'clubs.index', 'create' => 'clubs.create', 'edit' => 'clubs.edit', 'store' => 'clubs.store', 'update' => 'clubs.update']]);

        Route::resource('categories', 'CategoryController');

        //TODO those routes should not exist -- removing
        Route::resource('/tournaments/{tournament}/teams', 'TeamController', ['names' => ['index' => 'teams.index', 'create' => 'teams.create', 'edit' => 'teams.edit', 'store' => 'teams.store', 'update' => 'teams.update']]);

        Route::resource('users', 'UserController', ['names' => [
            'index' => 'users.index',
            'show' => 'users.show',
            'create' => 'users.create',
            'edit' => 'users.edit',
            'store' => 'users.store',
            'update' => 'users.update'
        ]]);

        Route::get('users/{user}/tournaments', [
            'uses' => 'UserController@getMyTournaments',
            'as' => 'users.tournaments'
        ]);


        Route::get('export', 'UserController@export');
        Route::resource('tournaments/{tournament}/users', 'CompetitorController', ['names' => ['index' => 'tournament.users.index', 'show' => 'tournament.users.show', 'create' => 'tournament.users.create', 'edit' => 'tournament.users.edit', 'store' => 'tournament.users.store', 'update' => 'tournament.users.update']]);
        Route::delete('tournaments/{tournamentId}/categories/{championshipId}/users/{userId}/delete', 'CompetitorController@deleteUser');
        Route::put('tournaments/{tournamentId}/categories/{championshipId}/users/{userId}/confirm', 'CompetitorController@confirmUser');

        Route::resource('invites', 'InviteController', ['names' => ['index' => 'invites.index', 'store' => 'invites.store', 'show' => 'invites.show']]);
        Route::post('invites/upload', 'InviteController@upload');
        Route::get('tournaments/{tournament}/invite', 'InviteController@create');


        Route::post('championships/{championship}/teams', 'TeamController@store')->name('team.store');


        // Other Admin Routes

        Route::get('logs', 'LogsController@index')->name('logs.index');
        Route::get('debug', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index')->name('debug.index');


//        Route::get('oauth', function(){
//           return view('auth/oauth2');
//        });

        Route::get('tournaments/{tournament}/trees/', 'TreeController@index')->name('tree.index');
        Route::get('tournaments/{tournament}/fights/', 'FightController@index')->name('fights.index');
        Route::get('championships/{championship}/tree/', 'TreeController@single')->name('tree.single');

        // PDF
        Route::get('championships/{championship}/tree/pdf', 'PDFController@tree')->name('tree_pdf');
        Route::get('championships/{championship}/scoresheet/pdf', 'PDFController@scoresheets')->name('sheet_pdf');

        Route::post('tournaments/{tournament}/trees/', 'TreeController@store')->name('tree.storeAll');
        Route::post('championships/{championshipId}/trees/', 'TreeController@store')->name('tree.store');;
        Route::put('championships/{championshipId}/trees/', 'TreeController@update')->name('tree.update');;

        Route::resource('tournaments/{tournament}/scoresheets', 'ScoreSheetController');


        Route::get('workingonit', function () {
            return view('workingonit');
        })->name('workingonit');



    });
Route::get('/auth/callback', function (Request $request) {
    $http = new GuzzleHttp\Client;

    $response = $http->post('https://laravel.dev/oauth/token', [
        'form_params' => [
            'grant_type' => 'authorization_code',
            'client_id' => '6',
            'client_secret' => 'A0srL90BUGWT0ATUeFFmDeiqTVkk4sH93PvMp5FS',
            'redirect_uri' => 'http://laravel.dev/auth/callback',
            'code' => $request->code,
        ],
    ]);

    return json_decode((string)$response->getBody(), true);
});


Auth::routes();

Route::get('/auth/oauth', function () {
    return view('auth.oauth');
});

Route::get('/oauth_test', function () {
    return view('oauth_ajax_test');
});

Route::get('/callback', function (Request $request) {
    $http = new GuzzleHttp\Client;

    $response = $http->post('https://laravel.dev/oauth/token', [
        'form_params' => [
            'grant_type' => 'authorization_code',
            'client_id' => '10',
            'client_secret' => 'LdI1CLUsWOqfsuyGApZSTbns0wQcoSpKE7LRzSPc',
            'redirect_uri' => 'https://laravel.dev/callback',
            'code' => $request->code,
        ],
    ]);

    return json_decode((string)$response->getBody(), true);
});

app/Association.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Collection;
use OwenIt\Auditing\Contracts\Auditable;
use stdClass;

class Association extends Model implements Auditable
{

    public $timestamps = true;
    protected $table = 'association';
    protected $guarded = ['id'];
    use SoftDeletes, \OwenIt\Auditing\Auditable;

    protected $dates = ['created_at', 'updated_at', 'deleted_at'];

    /**
     * Same than fillSelect, but with VueJS Format
     * @param $user
     * @param $federationId
     * @return Collection
     */
    public static function fillSelectForVueJs($user, $federationId)
    {
        $associations = Association::where('federation_id', $federationId)
            ->get(['id as value', 'name as text']);
        if (sizeof($associations) == 0) {
            $object = new stdClass;
            $object->value = 0;
            $object->text = trans('structures.no_association_yet');
            $associations->push($object);
        };
        return $associations;
    }

    protected static function boot()
    {
        parent::boot();
    }

    /**
     * An association has only 1 President
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function president()
    {
        return $this->hasOne(User::class, 'id', 'president_id');
    }

    /**
     * An association has Many Clubs
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function clubs()
    {
        return $this->hasMany(Club::class);
    }

    /**
     * An association belongs To a Federations
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function federation()
    {
        return $this->belongsTo(Federation::class);
    }

    /**
     * Filter the assocation List depending on the user type
     * Ex : SuperAdmin See all, Federation President only see his Associations, etc
     * @param $query
     * @param User $user
     */
    public function scopeForUser($query, User $user)
    {
        // Limit association to the same country
        if (!$user->isSuperAdmin()) {
            $query->whereHas('federation', function ($query) use ($user) {
                $query->where('country_id', $user->country_id);
            });
        }
    }



    /**
     * Check if an Association is in the same Federation than a Federation President
     * @param User $user
     * @return bool
     */
    public function belongsToFederationPresident(User $user)
    {
        if ($user->isFederationPresident() &&
            $user->federationOwned != null &&
            $this->federation->id == $user->federationOwned->id
        )
            return true;
        return false;
    }

    /**
     * Check if an Association is in the same Association than a Association President
     * @param User $user
     * @return bool
     */
    public function belongsToAssociationPresident(User $user)
    {
        if ($user->isAssociationPresident() &&
            $user->associationOwned != null &&
            $this->id == $user->associationOwned->id
        ) {
            return true;
        }
        return false;
    }

}

app/Http/Controllers/AssociationController.php
<?php

namespace App\Http\Controllers;

use App\Association;
use App\Federation;
use App\Http\Requests\AssociationRequest;
use App\User;
use Illuminate\Auth\Access\AuthorizationException;
use Illuminate\Database\QueryException;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\RedirectResponse;
use Illuminate\Support\Collection;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Request;
use Illuminate\Support\Facades\Response;
use Illuminate\Support\Facades\View;

class AssociationController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Collection|View
     */
    public function index()
    {
        $associations = Association::forUser(auth()->user());
        if (Request::ajax()) {
            return $associations->pluck('name', 'id')->prepend('-', 0);
        }
        $associations = $associations->where('id', '>', 1)->get();
        return view('associations.index', compact('associations'));

    }


    /**
     * Show the form for creating a new resource.
     * @return View
     * @throws AuthorizationException
     */
    public function create()
    {
        $association = new Association;
        $federation = new Collection;

        $users = User::forUser(Auth::user())->pluck('name', 'id')->prepend('-', 0);
        $federations = Federation::forUser(Auth::user())->pluck('name', 'id');
        $submitButton = trans('core.addModel', ['currentModelName' => trans_choice('structures.association', 1)]);
        return view('associations.form', compact('association', 'users', 'federation', 'federations', 'submitButton')); //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param AssociationRequest $request
     * @return Response|RedirectResponse
     * @throws AuthorizationException
     */
    public function store(AssociationRequest $request)
    {
        try {
            if ($request->president_id == 0)
                $request->merge(['president_id' => null]);

            $association = Association::create($request->all());
            if (Request::ajax()) {
                return Response::json(['msg' => trans('msg.association_create_successful', ['name' => $association->name]), 'status' => 'success', 'data' => $association], 200);
            } else {
                $msg = trans('msg.association_create_successful', ['name' => $association->name]);
                flash()->success($msg);
                return redirect(route("associations.index"));
            }
        } catch (QueryException $e) {
            if (Request::ajax()) {
                return Response::json(['msg' => $e], 500);
            } else {
                $user = User::find($request->president_id);
                $msg = trans('msg.association_president_already_exists', ['user' => $user->name]);
                flash()->error($msg);
                return redirect()->back();
            }
        }
    }


    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return View
     */
    public function show($id)
    {
        $association = Association::findOrFail($id);
        return view('associations.show', compact('association'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return View
     * @throws AuthorizationException
     */
    public function edit($id)
    {
        $association = Association::findOrFail($id);
        $federation = $association->federation;

        if (Auth::user()->cannot('edit', $association)) {
            throw new AuthorizationException();
        }

        $users = User::forUser(Auth::user())->pluck('name', 'id')->prepend('-', 0);
        $federations = Federation::forUser(Auth::user())->pluck('name', 'id');

        return view('associations.form', compact('association', 'users', 'federations', 'federation'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param AssociationRequest|Request $request
     * @param  int $id
     * @return Response|RedirectResponse
     * @throws AuthorizationException
     */
    public function update(AssociationRequest $request, $id)
    {
        $association = Association::findOrFail($id);

        if (Auth::user()->cannot('update', $association)) {
            throw new AuthorizationException();
        }
        try {
            if ($request->president_id == 0)
                $request->merge(['president_id' => null]);

            $association->update($request->all());
            $msg = trans('msg.association_edit_successful', ['name' => $association->name]);
            flash()->success($msg);
            return redirect(route('associations.index'));

        } catch (QueryException $e) {
            $user = User::find($request->president_id);
            $msg = trans('msg.association_president_already_exists', ['user' => $user->name]);
            flash()->error($msg);
            return redirect()->back();

        }

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param $associationId
     * @return JsonResponse
     */
    public function destroy($associationId)
    {
        $association = Association::find($associationId);

        if ($association->delete()) {
            return Response::json(['msg' => trans('msg.association_delete_successful', ['name' => $association->name]), 'status' => 'success']);
        } else {
            return Response::json(['msg' => trans('msg.association_delete_error', ['name' => $association->name]), 'status' => 'error']);
        }
    }

    /**
     * @param $id
     * @return JsonResponse
     */
    public function restore($id)
    {
        $association = Association::withTrashed()->find($id);
        if ($association->restore()) {
            return Response::json(['msg' => trans('msg.association_restored_successful', ['name' => $association->name]), 'status' => 'success']);
        } else {
            return Response::json(['msg' => trans('msg.association_restored_error', ['name' => $association->name]), 'status' => 'error']);
        }
    }


    public function changePresident()
    {
        // Open Transaction
        // Get the current president
        // Set the new president
        // Save
        // Close transaction
    }
}

resources/views/associations/form.blade.php
@extends('layouts.dashboard')
@section('title')
    @if (isset($association->id))
        <title>{{ trans('core.edit') .' '.$association->name }}</title>
    @else
        <title>{{ trans('structures.association.add') }}</title>
    @endif
@stop

@section('breadcrumbs')
    @if (isset($association->id))
        {!! Breadcrumbs::render('associations.edit',$association) !!}
    @else
        {!! Breadcrumbs::render('associations.create') !!}
    @endif


@stop
@section('content')
    @include("errors.list")
    <?php
    $appURL = (app()->environment() == 'local' ? getenv('URL_BASE') : config('app.url'));
    ?>

    @if (!is_null($association->id))
        @include('layouts.displayMenuMyEntitiesOnTop')
    @endif
    <!-- Detached content -->

    <div class="row">
        <div class="col-md-8 col-md-offset-2">
        @if (!is_null($association->id))
            {!! Form::model($association,
                                    ['method'=>"PATCH",
                                    "action" => ["AssociationController@update", $association->id],
                                    'id' => 'form']) !!}


        @else

            {!! Form::open(['url'=>route('associations.store')]) !!}

        @endif
        <!-- Simple panel 1 : General Data-->


            <div class="panel panel-flat">

                <div class="panel-body">
                    <div class="container-fluid">


                        <fieldset title="{{Lang::get('core.general_data')}}">
                            <legend class="text-semibold">{{Lang::get('core.general_data')}}</legend>

                            <div class="form-group">
                                {!!  Form::label('name', trans('core.name'),['class' => 'text-bold' ]) !!}
                                <br/>
                                {!!  Form::text('name', old('name'), ['class' => 'form-control']) !!}

                            </div>


                            {!!  Form::label('federation', trans_choice('structures.federation',1),['class' => 'text-bold' ]) !!}
                            {!!  Form::select('federation_id',$federations,old('federation_id'),['class' => 'form-control']) !!}


                            <br/>
                            {!!  Form::label('president', trans('structures.association.president'),['class' => 'text-bold' ]) !!}
                            @if(sizeof($users)==0)
                                {!!  Form::text('president_id', trans('structures.association.no_user_in_this_country'), ['class' => 'form-control ','disabled']) !!}
                                {!!  Form::hidden('president_id', 1) !!}

                            @else
                                {!!  Form::select('president_id', $users,old('president_id'), ['class' => 'form-control']) !!}
                            @endif


                            <br/>
                            {!!  Form::label('address', trans('structures.association.address'),['class' => 'text-bold' ]) !!}
                            <div class="input-group">
                                {!!  Form::input('text', 'address', old('address'), ['class' => 'form-control address']) !!}
                                <span class="input-group-addon"><i class="icon-envelop3"></i></span>

                            </div>

                            <br/>
                            {!!  Form::label('phone', trans('structures.association.phone'),['class' => 'text-bold' ]) !!}


                            <div class="input-group">
                                {!!  Form::input('text', 'phone', old('phone'), ['class' => 'form-control phone']) !!}
                                <span class="input-group-addon"><i class="icon-phone"></i></span>
                            </div>

                        </fieldset>


                    </div>
                    <br/>
                    <div align="right">
                        <button type="submit" class="btn btn-success" id="save"><i></i>{{trans("core.save")}}</button>
                    </div>
                </div>
            </div>
            {!! Form::close() !!}
        </div>
    </div>
@stop
@section('scripts_footer')
    {!! JsValidator::formRequest('App\Http\Requests\AssociationRequest') !!}
@stop

resources/views/associations/index.blade.php
@extends('layouts.dashboard')
@section('title')
    <title>{{ trans_choice('structures.association',2) }}</title>
@stop

@section('title')

@stop
@section('breadcrumbs')
    {!! Breadcrumbs::render('associations.index') !!}
@stop

@section('content')
    <!-- Submenu -->
    @include('layouts.displayMenuMyEntitiesOnTop')
    <!-- /Submenu -->


    <div class="container-fluid">

        @if (sizeof($associations)==0)
            @include('layouts.noAssociations')
        @else


            <table class="table table-togglable table-hover">
                <thead>
                <tr>

                    <th data-toggle="true">{{ trans_choice('core.name',1) }}</th>
                    <th class="text-center" data-hide="phone">{{ trans_choice('structures.federation',1) }}</th>
                    <th class="text-center" data-hide="phone">{{ trans('structures.association.president') }}</th>
                    <th class="text-center" data-hide="phone">{{ trans('core.email') }}</th>
                    <th class="text-center" data-hide="all">{{ trans('structures.association.address') }}</th>
                    <th class="text-center" data-hide="all">{{ trans('structures.association.phone') }}</th>
                    <th class="text-center" data-hide="phone">{{ trans('core.country') }}</th>
                    <th class="text-center" data-hide="phone">{{ trans('core.action') }}</th>

                </tr>
                </thead>
                @foreach($associations as $association)
                    <tr>
                        <td>
                            @if (Auth::user()->isSuperAdmin() || Auth::user()->isFederationPresident())
                                <a href="{!!   URL::action('AssociationController@edit',  $association->id) !!}">{{ $association->name }}</a>
                            @else
                                {{ $association->name }}
                            @endif
                        </td>
                        <td align="center">{{ $association->federation != null ? $association->federation->name : " - "}}</td>
                        <td align="center">{{ $association->president != null ? $association->president->name : " - "}}</td>
                        <td align="center">{{ $association->president != null ? $association->president->email : " - " }}</td>
                        <td align="center">{{ $association->address }}</td>
                        <td align="center">{{ $association->phone }}</td>
                        <td align="center">{!!   $association->federation !=null && $association->federation->country !=null? "<img src=/images/flags/".$association->federation->country->flag. " />" : '&nbsp;' !!}</td>
                        <td align="center">

                            @can('edit', $association)
                                <a href="{{URL::action('AssociationController@edit', $association->id)}}"><i
                                            class="icon icon-pencil7"></i></a>
                            @endcan
                            @can('delete', $association)
                                {!! Form::open(['method' => 'DELETE', 'id' => 'formDeleteAssociation', 'action' => ['AssociationController@destroy', $association->id], 'style'=>"display: inline-block"]) !!}
                                {!! Form::button( '<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit','class' => 'btn text-warning-600 btn-flat btnDeleteAssociation', 'id'=>'delete_'.$association->id, 'data-id' => $association->id ] ) !!}
                                {!! Form::close() !!}
                            @endcan
                        </td>

                    </tr>

                @endforeach


            </table>
        @endif


    </div>

    @include("errors.list")
@stop
@section('scripts_footer')
    {!! Html::script('js/pages/header/footable.js') !!}

    <script>
        var url = "{{ URL::action('AssociationController@index') }}";
    </script>
    {!! Html::script('js/pages/footer/associationIndexFooter.js') !!}
@stop